config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard/welcome#index'

  namespace :dashboard do
    get 'welcome/index'
    get 'statistics/index'
    get 'alerts/index'
    resources :patients do
      resources :appointments do
        resources :skin_folds
        member do
          get 'duplicate'
        end
      end
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/appointment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: appointments
#
#  id                    :bigint           not null, primary key
#  appointment_date      :date
#  appointment_status_cd :string           default("no")
#  appointment_type_cd   :string
#  density               :decimal(, )      default(0.0)
#  fat                   :decimal(, )      default(0.0)
#  mass                  :decimal(, )      default(0.0)
#  organs                :decimal(, )      default(0.0)
#  payment_status_cd     :string           default("yes")
#  plan_type_cd          :string
#  price                 :decimal(, )      default(0.0)
#  water                 :decimal(, )      default(0.0)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  patient_id            :bigint           not null
#
# Indexes
#
#  index_appointments_on_patient_id  (patient_id)
#
# Foreign Keys
#
#  fk_rails_...  (patient_id => patients.id)
#
class Appointment < ApplicationRecord
  scope :no, -> { where(appointment_status_cd: :no) }
  scope :no_show, -> { where(appointment_status_cd: :no_show) }
  scope :days_30_past, -> { where(appointment_date: Time.zone.today - 30..Time.zone.today) }
  scope :days_7_future, -> { where(appointment_date: Time.zone.today + 1..Time.zone.today + 7) }
  belongs_to :patient
  has_one :skin_fold, dependent: :destroy
  paginates_per 5
  validates_presence_of %w[appointment_date appointment_type patient]
  money_field :price
  after_create :create_skin_fold
  accepts_nested_attributes_for :skin_fold, allow_destroy: true

  PLAN_TYPES = %i[basic balance freedom].freeze
  as_enum :plan_type, PLAN_TYPES, prefix: true, map: :string
  translate_enum :plan_type

  def create_skin_fold
    SkinFold.find_or_initialize_by(appointment_id: id)
  end

  amoeba do
    enable
  end

  APPOINTMENT_TYPE = %i[appointment return].freeze
  as_enum :appointment_type, APPOINTMENT_TYPE, map: :string
  translate_enum :appointment_type

  PAYMENT_STATUS = %i[yes no].freeze
  as_enum :payment_status, PAYMENT_STATUS, map: :string
  translate_enum :payment_status

  APPOINTMENT_STATUS = %i[yes no no_show].freeze
  as_enum :appointment_status, APPOINTMENT_STATUS, map: :string
  translate_enum :appointment_status

  def age_on_appointment
    ad = appointment_date
    dob = patient.birth_date
    ad.year - dob.year - (ad.month > dob.month || (ad.month == dob.month && ad.day >= dob.day) ? 0 : 1)
  end
end

app/controllers/dashboard/alerts_controller.rb
# frozen_string_literal: true

module Dashboard
  class AlertsController < DashboardController
    def index
      @future_appointments = Appointment.days_7_future.count
      @future_appointments_hash = Appointment.days_7_future
      @past_appointments = Appointment.no.days_30_past.count
      @past_appointments_hash = Appointment.no.days_30_past
      @no_show_appointments = Appointment.no_show.days_30_past.count
      @no_show_appointments_hash = Appointment.no_show.days_30_past
    end
  end
end

app/controllers/dashboard/appointments_controller.rb
# frozen_string_literal: true

module Dashboard
  class AppointmentsController < DashboardController
    before_action :set_patient
    before_action :set_appointment, only: %i[show edit update destroy duplicate]

    def index; end

    def show
      @skin_fold = @appointment.skin_fold
    end

    def new
      @appointment = @patient.appointments.build
      respond_to do |format|
        format.js
      end
    end

    def duplicate
      new_appointment = @appointment.amoeba_dup
      new_appointment.update!(appointment_date: Time.zone.now)
      new_appointment.save
      new_appointment.skin_fold.update!(appointment: new_appointment)
      redirect_to [:dashboard, @patient], notice: 'Consulta Duplicada com Sucesso'
    end

    def edit
      respond_to do |format|
        format.js
      end
    end

    def create
      @appointment = @patient.appointments.build(appointment_params)

      respond_to do |format|
        if @appointment.save
          format.html { redirect_to [:dashboard, @patient], notice: 'Consulta criada com sucesso!' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @appointment.update(appointment_params)
          format.html { redirect_to [:dashboard, @patient], notice: 'Consulta editada com sucesso' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @appointment.destroy
      respond_to do |format|
        format.html { redirect_to [:dashboard, @patient], notice: 'Consulta excluída com sucesso' }
      end
    end

    private

    def set_appointment
      @appointment = @patient.appointments.find(params[:id])
    end

    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    def appointment_params
      params.require(:appointment).permit(:appointment_date, :appointment_type, :patient_id, :appointment_status,
                                          :price, :payment_status, :formatted_price, :patient, :plan_type, :status)
    end
  end
end

app/controllers/dashboard/patients_controller.rb
# frozen_string_literal: true

module Dashboard
  class PatientsController < DashboardController
    before_action :set_patient, only: %i[show edit update destroy]

    # GET /patients
    # GET /patients.json
    def index
      @q = Patient.ransack(params[:q])
      @patients = @q.result.order(:first_name).page(params[:page])
    end

    # GET /patients/1
    # GET /patients/1.json
    def show
      @appointments = @patient.appointments.order('appointment_date DESC').page(params[:page])
    end

    # GET /patients/new
    def new
      @patient = Patient.new
      respond_to do |format|
        format.html
        format.js
      end
    end

    # GET /patients/1/edit
    def edit; end

    # POST /patients
    # POST /patients.json
    def create
      @patient = Patient.new(patient_params)

      respond_to do |format|
        if @patient.save
          format.html { redirect_to dashboard_patients_path, notice: "Paciente #{@patient.first_name} #{@patient.last_name} cadastrado com sucesso!" }
          format.json { render :show, status: :created, location: @patient }
        else
          format.html { render :new }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /patients/1
    # PATCH/PUT /patients/1.json
    def update
      respond_to do |format|
        if @patient.update(patient_params)
          format.html { redirect_to dashboard_patients_path, notice: "Paciente #{@patient.first_name} editado com sucesso!" }
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /patients/1
    # DELETE /patients/1.json
    def destroy
      @patient.destroy
      respond_to do |format|
        format.html { redirect_to patients_url, notice: 'Paciente excluído com sucesso!' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :birth_date, :gender, :street, :number,
                                      :state, :country, :city, :cpf, :obs, :phone, :user_id, :email,
                                      :avatar, :avatar_cache, :remove_avatar, :professionm, :status,
                                      :plan_type)
    end
  end
end

app/controllers/dashboard/skin_folds_controller.rb
# frozen_string_literal: true

module Dashboard
  class SkinFoldsController < DashboardController
    before_action :set_appointment, :set_patient
    before_action :set_skin_fold, only: %i[show edit update]

    def index; end

    def show; end

    def edit
      respond_to do |format|
        format.js
      end
    end

    def update
      respond_to do |format|
        if @skin_fold.update(skin_fold_params)
          Process::Utils::Fat.new(@skin_fold, @skin_fold.appointment.age_on_appointment).call
          format.html { redirect_to [:dashboard, @patient, @skin_fold.appointment], notice: 'Antropometria editada com sucesso' }
        else
          format.html { render :edit }
        end
      end
    end

    private

    def set_skin_fold
      @skin_fold = @appointment.skin_fold
    end

    def set_appointment
      @appointment = Appointment.find(params[:appointment_id])
    end

    def set_patient
      @patient = @appointment.patient
    end

    def skin_fold_params
      params.require(:skin_fold).permit(:fold1, :fold2, :fold3, :fold4, :measure1, :measure2, :appointment,
                                        :measure3, :measure4, :measure5, :fold5, :fold6, :fold7, :appointment, :weight, :height)
    end
  end
end

app/controllers/dashboard/statistics_controller.rb
# frozen_string_literal: true

module Dashboard
  class StatisticsController < DashboardController
    def index
      @patient_male = Patient.all.where(gender: 'male').count
      @patient_female = Patient.all.where(gender: 'female').count
      @active_male = Patient.where(status_cd: :active, gender: 'male').count
      @active_female = Patient.where(status_cd: :active, gender: 'female').count
      @patients = Patient.all
    end
  end
end

app/controllers/dashboard/welcome_controller.rb
# frozen_string_literal: true

module Dashboard
  class WelcomeController < DashboardController
    def index
      @count_patients = Patient.count
      @count_appointments = Appointment.count
      @total_earned = Appointment.yes.sum(:price)
      @total_to_earn = Appointment.nos.sum(:price)
      @appointments_per_month = Appointment.all.group_by_month(:appointment_date, last: 12, format: '%b %y').count
      @earned_per_month = Appointment.yes.group_by_month(:appointment_date, last: 12, format: '%b %y').sum(:price)
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/dashboard/appointments_helper.rb
# frozen_string_literal: true

module Dashboard
  module AppointmentsHelper
  end
end

app/helpers/dashboard/pacients_helper.rb
# frozen_string_literal: true

module Dashboard
  module PacientsHelper
  end
end

app/helpers/dashboard/patients_helper.rb
# frozen_string_literal: true

module Dashboard
  module PatientsHelper
  end
end

app/helpers/dashboard/statistics_helper.rb
# frozen_string_literal: true

module Dashboard
  module StatisticsHelper
  end
end

app/helpers/dashboard/welcome_helper.rb
# frozen_string_literal: true

module Dashboard
  module WelcomeHelper
  end
end

app/views/dashboard/appointments/_edit.html.erb
<div class="modal fade bd-example-modal-md show" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" style="display: block; padding-right: 15px;">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-body">
        <%= render 'form', appointment: @appointment %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/appointments/_form.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Consulta</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="card card-default">
    <div class="card-body">
      <div class="row">
        <div class="col-md-12">
          <%= simple_form_for [:dashboard, @patient, @appointment] do |f| %>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.input :appointment_date, as: :date, html5: true %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.input :appointment_type, as: :select, collection: Appointment.translated_appointment_types %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.input :formatted_price, as: :string, input_html: { class: 'input--brl-money input--brl-money-public' } %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.input :plan_type, as: :select, collection: Appointment::translated_plan_types %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.input :payment_status, as: :select, collection: Appointment.translated_payment_statuses, include_blank: false %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.input :appointment_status, as: :select, collection: Appointment.translated_appointment_statuses, include_blank: false %>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <%= f.button :submit %>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/dashboard/appointments/edit.html.erb
<%= render 'form', appointment: @appointment %>

app/views/dashboard/appointments/edit.js.erb
$("#modal-window").html("<%= escape_javascript(render 'edit') %>");

app/views/dashboard/appointments/new.html.erb
<%= render 'form', appointment: @appointment %>

app/views/dashboard/appointments/show.html.erb
<!-- Content Header (Page header) -->
</br>
<section class="content">
  <div class="card">
    <div class="card-header">
      <h2 class="card-title">Paciente: <%= @appointment.patient.full_name %> | <%= @appointment.translated_appointment_type %>: <%=l @appointment.appointment_date, format: :default %></h2>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-2">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Itens</h3>
              <div class="card-tools">
                <!-- <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i> -->
                </button>
              </div>
            </div>
            <div class="card-body p-0" style="display: block;">
              <ul class="nav nav-pills flex-column">
                <li class="nav-item">
                  <%= link_to root_path, class:"nav-link" do %>
                    <i class="far fa-envelope"></i> Anamnese
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to edit_dashboard_patient_appointment_skin_fold_path(@patient.id, @appointment.id),  {'class' => 'nav-link', remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} do %>
                    <i class="far fa-envelope"></i> Composição
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-10 col-md-10 col-lg-10 order-2 order-md-1">
          <div class="row">
            <div class="col-12 col-sm-4">
              <div class="info-box bg-light">
                <div class="info-box-content">
                  <span class="info-box-text text-center text-muted">Idade na consulta</span>
                  <span class="info-box-number text-center text-muted mb-0"><%= @appointment.age_on_appointment %> anos</span>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-4">
              <div class="info-box bg-light">
                <div class="info-box-content">
                  <span class="info-box-text text-center text-muted">Peso atual</span>
                  <span class="info-box-number text-center text-muted mb-0"><%= @skin_fold.try(:weight) %> Kg</span>
                </div>
              </div>
            </div>
            <div class="col-12 col-sm-4">
              <div class="info-box bg-light">
                <div class="info-box-content">
                  <span class="info-box-text text-center text-muted">Gordura</span>
                  <span class="info-box-number text-center text-muted mb-0"><%= @appointment.try(:fat) %>%<span>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <h4>Resumo da Consulta</h4>
            </div>
            <p>Aqui poderia ter gráfico da evolução</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div id="modal-window" class="modal hide" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>