config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'dashboard/welcome#index'

  namespace :dashboard do
    get 'welcome/index'
    get 'statistics/index'
    get 'alerts/index'
    resources :patients do
      resources :appointments do
        resources :skin_folds
        member do
          get 'duplicate'
        end
      end
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/patient.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: patients
#
#  id           :bigint           not null, primary key
#  avatar       :string
#  birth_date   :date
#  city         :string
#  country      :string
#  cpf          :string
#  email        :string
#  first_name   :string
#  gender       :string
#  last_name    :string
#  number       :integer
#  obs          :text
#  phone        :string
#  plan_type_cd :string
#  profession   :string
#  state        :string
#  status_cd    :string
#  street       :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :bigint           not null
#
# Indexes
#
#  index_patients_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Patient < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  validates_presence_of %w[first_name last_name birth_date user]
  paginates_per 12
  mount_uploader :avatar, AvatarUploader
  after_create :set_patient_status, :setup_patient
  accepts_nested_attributes_for :appointments, allow_destroy: true

  STATUSES = %i[active inactive].freeze
  as_enum :status, STATUSES, prefix: true, map: :string
  translate_enum :status

  PLAN_TYPES = %i[basic balance freedom].freeze
  as_enum :plan_type, PLAN_TYPES, prefix: true, map: :string
  translate_enum :plan_type

  def setup_patient
    appointment = Appointment.create!(appointment_date: Time.zone.now, patient_id: id, appointment_type: :appointment, plan_type: plan_type)
    SkinFold.create!(appointment: appointment)
  end

  def set_patient_status
    update!(status: :active)
  end

  def full_name
    [first_name, last_name].join(' ')
  end

  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new(
      '||',
      Arel::Nodes::InfixOperation.new(
        '||',
        parent.table[:first_name], Arel::Nodes.build_quoted(' ')
      ),
      parent.table[:last_name]
    )
  end

  def age
    now = Time.zone.now
    dob = birth_date
    now.year - dob.year - (now.month > dob.month || (now.month == dob.month && now.day >= dob.day) ? 0 : 1)
  end

  def self.average_male
    male = where(gender: 'male')
    return 0 if male.count.zero?

    male.sum(&:age) / male.count
  end

  def self.average_female
    female = where(gender: 'female')
    return 0 if female.count.zero?

    female.sum(&:age) / female.count
  end
end

app/controllers/dashboard/alerts_controller.rb
# frozen_string_literal: true

module Dashboard
  class AlertsController < DashboardController
    def index
      @future_appointments = Appointment.days_7_future.count
      @future_appointments_hash = Appointment.days_7_future
      @past_appointments = Appointment.no.days_30_past.count
      @past_appointments_hash = Appointment.no.days_30_past
      @no_show_appointments = Appointment.no_show.days_30_past.count
      @no_show_appointments_hash = Appointment.no_show.days_30_past
    end
  end
end

app/controllers/dashboard/appointments_controller.rb
# frozen_string_literal: true

module Dashboard
  class AppointmentsController < DashboardController
    before_action :set_patient
    before_action :set_appointment, only: %i[show edit update destroy duplicate]

    def index; end

    def show
      @skin_fold = @appointment.skin_fold
    end

    def new
      @appointment = @patient.appointments.build
      respond_to do |format|
        format.js
      end
    end

    def duplicate
      new_appointment = @appointment.amoeba_dup
      new_appointment.update!(appointment_date: Time.zone.now)
      new_appointment.save
      new_appointment.skin_fold.update!(appointment: new_appointment)
      redirect_to [:dashboard, @patient], notice: 'Consulta Duplicada com Sucesso'
    end

    def edit
      respond_to do |format|
        format.js
      end
    end

    def create
      @appointment = @patient.appointments.build(appointment_params)

      respond_to do |format|
        if @appointment.save
          format.html { redirect_to [:dashboard, @patient], notice: 'Consulta criada com sucesso!' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @appointment.update(appointment_params)
          format.html { redirect_to [:dashboard, @patient], notice: 'Consulta editada com sucesso' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @appointment.destroy
      respond_to do |format|
        format.html { redirect_to [:dashboard, @patient], notice: 'Consulta excluída com sucesso' }
      end
    end

    private

    def set_appointment
      @appointment = @patient.appointments.find(params[:id])
    end

    def set_patient
      @patient = Patient.find(params[:patient_id])
    end

    def appointment_params
      params.require(:appointment).permit(:appointment_date, :appointment_type, :patient_id, :appointment_status,
                                          :price, :payment_status, :formatted_price, :patient, :plan_type, :status)
    end
  end
end

app/controllers/dashboard/patients_controller.rb
# frozen_string_literal: true

module Dashboard
  class PatientsController < DashboardController
    before_action :set_patient, only: %i[show edit update destroy]

    # GET /patients
    # GET /patients.json
    def index
      @q = Patient.ransack(params[:q])
      @patients = @q.result.order(:first_name).page(params[:page])
    end

    # GET /patients/1
    # GET /patients/1.json
    def show
      @appointments = @patient.appointments.order('appointment_date DESC').page(params[:page])
    end

    # GET /patients/new
    def new
      @patient = Patient.new
      respond_to do |format|
        format.html
        format.js
      end
    end

    # GET /patients/1/edit
    def edit; end

    # POST /patients
    # POST /patients.json
    def create
      @patient = Patient.new(patient_params)

      respond_to do |format|
        if @patient.save
          format.html { redirect_to dashboard_patients_path, notice: "Paciente #{@patient.first_name} #{@patient.last_name} cadastrado com sucesso!" }
          format.json { render :show, status: :created, location: @patient }
        else
          format.html { render :new }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /patients/1
    # PATCH/PUT /patients/1.json
    def update
      respond_to do |format|
        if @patient.update(patient_params)
          format.html { redirect_to dashboard_patients_path, notice: "Paciente #{@patient.first_name} editado com sucesso!" }
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /patients/1
    # DELETE /patients/1.json
    def destroy
      @patient.destroy
      respond_to do |format|
        format.html { redirect_to patients_url, notice: 'Paciente excluído com sucesso!' }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :birth_date, :gender, :street, :number,
                                      :state, :country, :city, :cpf, :obs, :phone, :user_id, :email,
                                      :avatar, :avatar_cache, :remove_avatar, :professionm, :status,
                                      :plan_type)
    end
  end
end

app/controllers/dashboard/skin_folds_controller.rb
# frozen_string_literal: true

module Dashboard
  class SkinFoldsController < DashboardController
    before_action :set_appointment, :set_patient
    before_action :set_skin_fold, only: %i[show edit update]

    def index; end

    def show; end

    def edit
      respond_to do |format|
        format.js
      end
    end

    def update
      respond_to do |format|
        if @skin_fold.update(skin_fold_params)
          Process::Utils::Fat.new(@skin_fold, @skin_fold.appointment.age_on_appointment).call
          format.html { redirect_to [:dashboard, @patient, @skin_fold.appointment], notice: 'Antropometria editada com sucesso' }
        else
          format.html { render :edit }
        end
      end
    end

    private

    def set_skin_fold
      @skin_fold = @appointment.skin_fold
    end

    def set_appointment
      @appointment = Appointment.find(params[:appointment_id])
    end

    def set_patient
      @patient = @appointment.patient
    end

    def skin_fold_params
      params.require(:skin_fold).permit(:fold1, :fold2, :fold3, :fold4, :measure1, :measure2, :appointment,
                                        :measure3, :measure4, :measure5, :fold5, :fold6, :fold7, :appointment, :weight, :height)
    end
  end
end

app/controllers/dashboard/statistics_controller.rb
# frozen_string_literal: true

module Dashboard
  class StatisticsController < DashboardController
    def index
      @patient_male = Patient.all.where(gender: 'male').count
      @patient_female = Patient.all.where(gender: 'female').count
      @active_male = Patient.where(status_cd: :active, gender: 'male').count
      @active_female = Patient.where(status_cd: :active, gender: 'female').count
      @patients = Patient.all
    end
  end
end

app/controllers/dashboard/welcome_controller.rb
# frozen_string_literal: true

module Dashboard
  class WelcomeController < DashboardController
    def index
      @count_patients = Patient.count
      @count_appointments = Appointment.count
      @total_earned = Appointment.yes.sum(:price)
      @total_to_earn = Appointment.nos.sum(:price)
      @appointments_per_month = Appointment.all.group_by_month(:appointment_date, last: 12, format: '%b %y').count
      @earned_per_month = Appointment.yes.group_by_month(:appointment_date, last: 12, format: '%b %y').sum(:price)
    end
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/dashboard/appointments_helper.rb
# frozen_string_literal: true

module Dashboard
  module AppointmentsHelper
  end
end

app/helpers/dashboard/pacients_helper.rb
# frozen_string_literal: true

module Dashboard
  module PacientsHelper
  end
end

app/helpers/dashboard/patients_helper.rb
# frozen_string_literal: true

module Dashboard
  module PatientsHelper
  end
end

app/helpers/dashboard/statistics_helper.rb
# frozen_string_literal: true

module Dashboard
  module StatisticsHelper
  end
end

app/helpers/dashboard/welcome_helper.rb
# frozen_string_literal: true

module Dashboard
  module WelcomeHelper
  end
end

app/views/dashboard/patients/_form.html.erb
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Paciente</h1>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
        </ol>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <div class="card card-solid">
    <div class="card-body">
    <div class="row">
      <div class="col-md-12">
        <%= simple_form_for [:dashboard, @patient] do |f| %>
          <div class="card-body">
            <div class="row">
              <div class="col-md-2">
                <div class="form-group">
                  <%= f.input :first_name %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= f.input :last_name %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= f.input :birth_date, as: :date, html5: true %>
                </div>
              </div>
              <div class="col-md-2">
                <div class="form-group">
                  <%= f.input :gender, label: 'Sexo', as: :select, collection: [['male', 'Masculino'], ['female', 'Feminino']], label_method: :last, value_method: :first, checked: @patient.gender, item_wrapper_class: 'inline' %>
                </div>
              </div>
              <div class="col-md-2">
                <div class="form-group">
                  <%= f.association :user, label_method: :first_name, value_method: :id, include_blank: false %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-3">
                <div class="form-group">
                  <%= f.input :cpf, input_html: { class: 'input--cpf' } %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= f.input :email, as: :email %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= f.input :phone, as: :tel, input_html: { class: 'phone' } %>
                </div>
              </div>
              <div class="col-md-3">
                <div class="form-group">
                  <%= f.input :plan_type, as: :select, collection: Patient::translated_plan_types %>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.input :city %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <%= f.input :state %>
                </div>
              </div>
              <div class="col-md-10">
                <div class="form-group">
                  <%= f.input :street %>
                </div>
              </div>
              <div class="col-md-2">
                <div class="form-group">
                  <%= f.input :number %>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <%= f.text_area :obs, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <%= f.label :avatar do %>
                  <%= f.file_field :avatar %>
                  <%= f.hidden_field :avatar_cache %>
                <% end %>
              </div>
            </div>
            <%= f.submit 'Salvar', class: 'btn btn-primary' %>
          </div>
      </div>
    </div>

    </div>
        <% end %>
  </div>
  </div>
  </div>
</section>

app/views/dashboard/patients/edit.html.erb
<%= render 'form', patient: @patient %>

app/views/dashboard/patients/index.html.erb
<!-- Content Header (Page header) -->
<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Pacientes</h1>
        <%= link_to 'Novo Paciente', new_dashboard_patient_path, class: 'btn btn-success' %>
      </div>
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <%= search_form_for [:dashboard, @q], class:"input-group md-form form-sm form-1 pl-0" do |f| %>
            <%= f.search_field :full_name_cont, class:"form-control my-0 py-1",
              type:"text", placeholder:"Buscar por nome" %>
            <div class="input-group-prepend">
              <%= f.submit class:"input-group-text purple lighten-3" %>
            </div>
          <% end %>
        </ol>
      </div>
    </div>
  </div><!-- /.container-fluid -->
</section>
<section class="content">
  <!-- Default box -->
  <div class="card card-solid">
    <div class="card-body pb-0">
      <div class="row d-flex align-items-stretch">
        <% @patients.each do |patient| %>
          <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
            <div class="card bg-light">
              <div class="card-header text-muted border-bottom-0">
                <h2 class="lead"><b><%= patient.full_name %></b></h2>
              </div>
              <div class="card-body pt-0">
                <div class="row">
                  <div class="col-7">
                    <p class="text-muted text-sm"><b><%= patient.age %> anos</b></p>
                    <ul class="ml-4 mb-0 fa-ul text-muted">
                      <li class="small">
                        <span class="fa-li"><i class="fas fa-lg fa-mobile-alt"></i>
                        </span> <%= patient.phone %>
                      </li>
                      <li class="medium" style="margin-left: 0px">
                          <%= plan_badge(patient.plan_type) %>
                      </li>
                      <li class="medium">
                          <%= status_badge(patient.status) %>
                      </li>
                    </ul>
                  </div>
                  <div class="col-5 text-center">
                    <%= image_tag(patient.avatar.url(:big), alt:"",
                        class:"img-circle img-fluid") %>
                  </div>
                </div>
              </div>
              <div class="card-footer">
                <div class="text-right">
                  <%= link_to dashboard_patient_path(patient), class:"btn btn-sm btn-primary" do %>
                    <i class="fas fa-user"></i> Perfil
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      <nav aria-label="Contacts Page Navigation">
        <ul class="pagination justify-content-center m-0">
          <%= paginate @patients %>
        </ul>
      </nav>
    </div>
    <!-- /.card-footer -->
  </div>
  <!-- /.card -->
</section>

app/views/dashboard/patients/new.html.erb
<%= render 'form', patient: @patient %>

app/views/dashboard/patients/show.html.erb
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3">
        <div class="card card-primary card-outline">
          <div class="card-body box-profile">
            <div class="text-center">
              <%= image_tag(@patient.avatar.url(:medium), alt: 'User profile picture', class:"profile-user-img img-fluid img-circle") if @patient.avatar %>
            </div>
            <h3 class="profile-username text-center"><%= @patient.first_name %> <%= @patient.last_name %></h3>
            <p class="text-muted text-center"><%= @patient.profession %></p>
            <ul class="list-group list-group-unbordered mb-3">
              <li class="list-group-item">
                <b>Plano: </b> <a class="float-right"><%= I18n.t(".activerecord.attributes.patient.plan_type_list.#{@patient.plan_type}") %></a>
              </li>
              <li class="list-group-item">
                <b>Idade: </b> <a class="float-right"><%= @patient.age %> anos</a>
              </li>
              <li class="list-group-item">
                <b>Altura:</b> <a class="float-right">xxx</a>
              </li>
              <li class="list-group-item">
                <b>Peso Atual:</b> <a class="float-right">xxx</a>
              </li>
            </ul>
            <%= link_to 'Editar Cadastro', edit_dashboard_patient_path(@patient), class:'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
      <div class="col-md-9">
        <div class="card">
          <div class="card-header p-2">
            <ul class="nav nav-pills">
              <li class="nav-item"><a class="nav-link active" href="#timeline" data-toggle="tab">Consultas</a></li>
              <li class="nav-item"><a class="nav-link" href="#activity" data-toggle="tab">Geral</a></li>
              <li class="nav-item"><a class="nav-link" href="#obs" data-toggle="tab">Observações</a></li>
              <li class="nav-item"><a class="nav-link" href="#evol" data-toggle="tab">Evolução</a></li>
            </ul>
          </div>
          <div class="card-body">
            <div class="tab-content">
              <div class="tab-pane" id="activity">
                <div class="row">
                  <div class="col-md-12">
                    <div class="card">
                      <div class="card-body">
                        <dl>
                          <dt>CPF</dt>
                          <dd><%= @patient.cpf %></dd>
                          <dt>Email</dt>
                          <dd><%= @patient.email %></dd>
                          <dt>Telefone</dt>
                          <dd><%= @patient.phone %></dd>
                          <dt>Endereço</dt>
                          <dd><%= @patient.street %>, <%= @patient.number %>. <%= @patient.city %>/<%= @patient.state %></dd>
                        </dl>
                      </div>

                    </div>

                  </div>

                </div>

              </div>

              <div class="active tab-pane" id="timeline">

                <div class="row">
                  <div class="col-12">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="card-title">
                          <%= link_to new_dashboard_patient_appointment_path(@patient, @appointment), remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class:"btn btn-success" do %>
                            <i class="fas fa-plus-circle"></i>  Nova Consulta
                          <% end %>
                        </h3>
                      </div>

                      <div class="card-body table-responsive p-0">
                        <table class="table table-hover text-nowrap">
                          <thead>
                            <tr>
                              <th>Data</th>
                              <th>Tipo</th>
                              <th>Preço</th>
                              <th>Plano</th>
                              <th>Pago?</th>
                              <th>Foi realizada?</th>
                              <th></th>
                            </tr>
                          </thead>
                          <tbody>
                            <% @appointments.each do |appointment| %>
                              <tr>
                                <td><%= l appointment.appointment_date, format: :default %></td>
                                <td><%= appointment.translated_appointment_type %></td>
                                <td><%= appointment.formatted_price %></td>
                                <td><%= I18n.t(".activerecord.attributes.appointment.plan_type_list.#{appointment.plan_type}") %></td>
                                <td><%= appointment.translated_payment_status %></td>
                                <td><%= appointment.translated_appointment_status %></td>
                                <td>
                                  <%= link_to dashboard_patient_appointment_path(@patient, appointment),
                                   class:"btn btn-success" do %>
                                    <i class="fas fa-user"></i>
                                  <% end %>
                                  <%= link_to edit_dashboard_patient_appointment_path(@patient, appointment), remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window',
                                   class:"btn btn-warning" do %>
                                    <i class="fas fa-edit"></i>
                                  <% end %>
                                  <%= link_to duplicate_dashboard_patient_appointment_path(@patient, appointment),
                                   class:"btn btn-warning" do %>
                                    <i class="fas fa-copy"></i>
                                  <% end %>
                                  <%= link_to dashboard_patient_appointment_path(@patient, appointment), data:{ confirm: "Tem certeza que deseja exluir a consulta do dia #{appointment.appointment_date}" }, method: :delete,
                                   class:"btn btn-danger" do %>
                                    <i class="fas fa-trash"></i>
                                  <% end %>
                                </td>
                              </tr>
                            <% end %>
                          </tbody>
                        </table>
                      </div>

                      <div class="card-footer">
                        <nav aria-label="Contacts Page Navigation">
                          <ul class="pagination justify-content-center m-0">
                            <%= paginate @appointments %>
                          </ul>
                        </nav>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="obs">
                <div class="row">
                  <div class="col-md-12">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="card-title">
                          <i class="fas fa-address-card"></i>
                          Observações
                        </h3>
                      </div>
                      <div class="card-body">
                        <dl>
                          <dd><%= @patient.obs %></dd>
                        </dl>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="tab-pane" id="evol">
                <div class="row">
                  <div class="col-md-12">
                    <div class="card">
                      <div class="card-header">
                        <h3 class="card-title">
                          <i class="fas fa-address-card"></i>
                          Evolução
                        </h3>
                      </div>
                      <div class="card-body">
                        <dl>
                          <% series = [
                            {name: "Gordura", data: @graph_fat}
                          ] %>
                          <% options = {
                            title: 'Properties Growth',
                            subtitle: 'Grouped Per Week',
                            xtitle: 'Week',
                            ytitle: 'Properties',
                            stacked: true
                          } %>
                          <%#= line_chart(series, options) %>
                        </dl>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<div id="modal-window" class="modal hide" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>